kind: Service
apiVersion: v1
metadata:
  name: background-svc
  labels:
    app: background-svc
spec:
  selector:
    app: background
  ports:
  - name: grpc
    port: 80
    targetPort: grpc
  type: ClusterIP