kind: Secret
apiVersion: v1
metadata:
  name: background-secret
data:
  DATABASE_CONNECTION_STRING: "dXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1UZXN0MTIzNDUgaG9zdD0xNzIuMTcuMC4xIHBvcnQ9NTQzMiBkYm5hbWU9cHJpbWVfbnVtYmVycyBzc2xtb2RlPWRpc2FibGU="