kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../base/
namespace: default
patchesStrategicMerge:
  - background-secrets.yaml
  - background-deployment.yaml
  - input-deployment.yaml